namespace Nemonuri.GenResx.Template.PostActions;

partial class GenResxTemplatePostAction
{
    private static string CreateGenResxPropsText() => 
$"""
<?xml version="1.0" encoding="utf-8"?>

<!-- This file was generated by: https://github.com/nemonuri/nemonuri-genresx -->

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

</Project>
""";
}